# Generated by Django 2.2.3 on 2019-07-08 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Xsg',
            fields=[
                ('sf', models.CharField(max_length=100)),
                ('ds', models.CharField(max_length=100)),
                ('zsddh', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('iccid', models.CharField(max_length=100)),
                ('ddsj', models.DateTimeField(max_length=100)),
                ('ddrq', models.DateField(max_length=100)),
                ('ddyf', models.DateField(max_length=100)),
                ('dghm', models.CharField(max_length=100)),
                ('khxm', models.CharField(max_length=100)),
                ('zjhm', models.CharField(max_length=100)),
                ('lxdh', models.CharField(max_length=100)),
                ('xb', models.CharField(max_length=100)),
                ('nl', models.CharField(max_length=100)),
                ('ddzt', models.CharField(max_length=100)),
                ('tcmc', models.CharField(max_length=100)),
                ('spmc', models.CharField(max_length=100)),
                ('tdsj', models.CharField(max_length=100)),
                ('tdyy', models.CharField(max_length=100)),
                ('khsj', models.CharField(max_length=100)),
                ('jhzt', models.CharField(max_length=100)),
                ('jhsj', models.DateTimeField()),
                ('jhrq', models.DateField()),
                ('jhyf', models.DateField()),
                ('tgqdbm', models.CharField(max_length=100)),
                ('tgqdmc', models.CharField(max_length=100)),
                ('tgfzrbm', models.CharField(max_length=100)),
                ('tgfzrmc', models.CharField(max_length=100)),
                ('qdbm', models.CharField(max_length=100)),
                ('qdmc', models.CharField(max_length=100)),
                ('fzrbm', models.CharField(max_length=100)),
                ('fzrmc', models.CharField(max_length=100)),
                ('jffs', models.CharField(max_length=100)),
                ('tjr', models.CharField(max_length=100)),
                ('tgrid', models.CharField(max_length=100)),
                ('msglb', models.CharField(max_length=100)),
                ('sxsjh', models.CharField(max_length=100)),
                ('shdz', models.CharField(max_length=100)),
                ('khfzqdlx', models.CharField(max_length=100)),
                ('sfecyx', models.CharField(max_length=100)),
            ],
        ),
    ]
