# Generated by Django 2.2.3 on 2019-07-08 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excel_factory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xsg',
            name='ddsj',
            field=models.DateTimeField(max_length=100, null=True),
        ),
    ]
