# Generated by Django 2.2.3 on 2019-07-08 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excel_factory', '0002_auto_20190708_2155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xsg',
            name='ddrq',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='xsg',
            name='ddsj',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='xsg',
            name='ddyf',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='xsg',
            name='jhrq',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='xsg',
            name='jhsj',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='xsg',
            name='jhyf',
            field=models.DateField(null=True),
        ),
    ]
