# Generated by Django 2.2.3 on 2019-07-09 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excel_factory', '0003_auto_20190708_2157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xsg',
            name='ddrq',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='xsg',
            name='ddsj',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='xsg',
            name='ddyf',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='xsg',
            name='jhrq',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='xsg',
            name='jhsj',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='xsg',
            name='jhyf',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
