# Generated by Django 2.2.3 on 2019-07-09 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excel_factory', '0004_auto_20190709_0857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xsg',
            name='ddzt',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='xsg',
            name='dghm',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='xsg',
            name='ds',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='xsg',
            name='fzrbm',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='xsg',
            name='fzrmc',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='xsg',
            name='iccid',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='xsg',
            name='jffs',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='xsg',
            name='jhzt',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='xsg',
            name='khfzqdlx',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='xsg',
            name='khsj',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='xsg',
            name='khxm',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='xsg',
            name='lxdh',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='xsg',
            name='msglb',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='xsg',
            name='nl',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='xsg',
            name='qdbm',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='xsg',
            name='qdmc',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='xsg',
            name='sf',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='xsg',
            name='sfecyx',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='xsg',
            name='shdz',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='xsg',
            name='spmc',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='xsg',
            name='sxsjh',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='xsg',
            name='tcmc',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='xsg',
            name='tdsj',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='xsg',
            name='tdyy',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='xsg',
            name='tgfzrbm',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='xsg',
            name='tgfzrmc',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='xsg',
            name='tgqdbm',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='xsg',
            name='tgqdmc',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='xsg',
            name='tgrid',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='xsg',
            name='tjr',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='xsg',
            name='xb',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='xsg',
            name='zjhm',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
