# Generated by Django 2.2.3 on 2019-07-11 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excel_factory', '0006_wyg'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cz',
            fields=[
                ('yhbh', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('dhhm', models.CharField(max_length=100, null=True)),
                ('fzbm', models.CharField(max_length=100, null=True)),
                ('rwsj', models.CharField(max_length=100, null=True)),
                ('rwyf', models.CharField(max_length=100, null=True)),
                ('zt', models.CharField(max_length=100, null=True)),
                ('cpbm', models.CharField(max_length=100, null=True)),
                ('cpmc', models.CharField(max_length=100, null=True)),
                ('ye', models.CharField(max_length=100, null=True)),
                ('zhtjsj', models.CharField(max_length=100, null=True)),
                ('scczje', models.CharField(max_length=100, null=True)),
                ('scczsj', models.CharField(max_length=100, null=True)),
                ('ljczje', models.CharField(max_length=100, null=True)),
                ('sfcz', models.CharField(max_length=100, null=True)),
                ('fzqy', models.CharField(max_length=100, null=True)),
                ('cbssfzr', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
