# Generated by Django 2.2.3 on 2019-07-11 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excel_factory', '0007_cz'),
    ]

    operations = [
        migrations.AddField(
            model_name='cz',
            name='scczrq',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cz',
            name='scczyf',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
