# Generated by Django 2.2.3 on 2019-07-12 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excel_factory', '0008_auto_20190711_1320'),
    ]

    operations = [
        migrations.CreateModel(
            name='Xm',
            fields=[
                ('fzrbm', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('Xm', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
