# Generated by Django 2.2.3 on 2019-07-12 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('excel_factory', '0009_xm'),
    ]

    operations = [
        migrations.RenameField(
            model_name='xm',
            old_name='Xm',
            new_name='xm',
        ),
    ]
